### ISSUE TITLE
Needs a license

### ISSUE THREAD

**Issue by est31** [lachlansneff/Metal#1]
Currently, this seems to have no license. I would suggest dual MIT/Apache-2.0 :).

**Comment by lachlansneff** [comment]
Cool. How to you suggest I add two licenses? Two license files?

**Comment by est31** [comment]
Yes, usually it is being done via two license files (LICENSE-APACHE and LICENSE-MIT).

See https://github.com/alexcrichton/toml-rs as an example.

Also, the README should contain a note about the license, you can copy the one from toml-rs. Last but not least, Cargo.toml has a field for the license. It should be sth like: `license = "MIT/Apache-2.0"`.

**Comment by lachlansneff** [comment]
Done.

**Comment by est31** [comment]
@lachlansneff thank you very much!
